server:
  port: 8081

dubbo:
  application:
    name: dubbo-order-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881

#mysql
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://106.15.63.194:3306/shop?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*xml